contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #fetchdata channel"
    url: https://nfcore.slack.com/channels/fetchdata
    about: Discussion about the nf-core/fetchdata pipeline
